{% set name = "circuitbreaker" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/circuitbreaker-{{ version }}.tar.gz
  sha256: 28110761ca81a2accbd6b33186bc8c433e69b0933d85e89f280028dbb8c1dd14

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - circuitbreaker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fabfuel/circuitbreaker
  summary: Python Circuit Breaker pattern implementation
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - manics
